apiVersion: apps/v1
kind: Deployment 
metadata:
 name: meudeployment
spec:
 replicas: 5 
 selector:
  matchLabels:
   app: web
 template:
  metadata:
   labels:
    app: web
  spec:
   containers:
   - name: site
     image: fabricioveronez/web-page:green
     ports:
     - containerPort: 80
